config_version = 14

[audio]
enable_sounds = true

[backdrop]
tint_intensity = 0.4999999888241291

[bar.default]
background_opacity = 0.79999998211860657
border = "on_surface_variant"
capsule = true
capsule_opacity = 0.0
capsule_padding = 8.0
capsule_radius = 2
capsule_thickness = 0.69999998807907104
end = [ "pill", "mini-docker", "privacy", "wallpaper", "clipboard", "volume", "brightness", "session" ]
margin_edge = 5
margin_ends = 12
radius = 2
start = [ "workspaces", "tray", "ram", "cpu", "widget", "status" ]

[calendar]
enabled = true

[control_center.calendar]
show_events_card = false

[desktop_widgets]
schema_version = 2
widget_order = []

    [desktop_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [desktop_widgets.widget]

[dock]
smart_auto_hide = true

[location]
address = "Severodvinsk"

[lockscreen_widgets]
enabled = false
schema_version = 2
widget_order = [ "lockscreen-login-box@winit", "lockscreen-login-box@HDMI-A-1" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1"]
    box_height = 196.0
    box_width = 810.0
    cx = 960.0
    cy = 898.0
    output = "HDMI-A-1"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

    [lockscreen_widgets.widget."lockscreen-login-box@winit"]
    box_height = 196.0
    box_width = 810.0
    cx = 472.50003051757812
    cy = 854.32830810546875
    output = "winit"
    placement_height = 1060.0
    placement_width = 945.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@winit".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

[plugins]
auto_update = "official"
enabled = [
    "noctalia/notes",
    "noctalia/wallhaven",
    "yocraft/desktop-launcher",
    "blackbartblues/audio-switcher",
    "nightwatch75/file-search",
    "8bury/mini-docker",
    "yuuto/calculator",
    "yuuto/arch-updater",
    "jrohland/claudecode",
    "3ri4ng0ld/ip-monitor",
    "andrey/happ-control"
]

    [[plugins.source]]
    kind = "git"
    location = "https://github.com/noctalia-dev/official-plugins"
    name = "official"

    [[plugins.source]]
    kind = "git"
    location = "https://github.com/noctalia-dev/community-plugins"
    name = "community"

    [[plugins.source]]
    kind = "path"
    location = "~/Plugins/happ-control"
    name = "happ-control"

[shell]
button_borders = false
card_borders = false
corner_radius_scale = 0.5000000074505806
font_family = "Noto Sans"
input_borders = false
niri_overview_type_to_launch_enabled = true
popup_borders = false

    [shell.launcher]
    pinned = [ "org.telegram.desktop", "Happ", "spotify-launcher", "firefox", "com.obsproject.Studio", "org.vinegarhq.Sober" ]
    show_app_origin_indicator = false

    [shell.panel]
    transparency_mode = "soft"

    [shell.shadow]
    direction = "up"

[theme]
builtin = "Tokyo-Night"
community_palette = "Atuel"
source = "community"
wallpaper_scheme = "dysfunctional"

    [theme.templates]
    builtin_ids = [ "alacritty", "btop", "cava", "gtk3", "gtk4", "ghostty" ]
    community_ids = [ "discord", "gimp", "fastfetch", "obs", "yazi" ]

[wallpaper]
directory = "/home/andrey/Pictures"

    [wallpaper.default]
    path = "/home/andrey/Pictures/wallhaven-yqkj3l.png"

    [wallpaper.last]
    path = "/home/andrey/Pictures/wallhaven-yqkj3l.png"

    [wallpaper.monitors.HDMI-A-1]
    path = "/home/andrey/Pictures/wallhaven-yqkj3l.png"

    [[wallpaper.favorite]]
    community_palette = "Atuel"
    palette_source = "community"
    path = "/home/andrey/Pictures/1.jpg"
    theme_mode = "dark"

    [[wallpaper.favorite]]
    builtin_palette = "Tokyo-Night"
    palette_source = "builtin"
    path = "/home/andrey/Pictures/wallhaven-e7kpl8.png"
    theme_mode = "dark"

[widget.active_window]
enabled = false

[widget.clipboard]
enabled = false

[widget.mini-docker]
type = "8bury/mini-docker:mini-docker"

[widget.pill]
type = "jrohland/claudecode:pill"

[widget.status]
type = "andrey/happ-control:status"

[widget.tray]
drawer = true
match_adjacent_spacing = true

[widget.wallpaper.actions]
right = "wallpaper-next"

[widget.widget]
type = "blackbartblues/audio-switcher:widget"